services:
  ProStriver-api:
    image: pranaypanakanti/prostriver:latest
    container_name: prostriver-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: api
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  alloy:
    image: grafana/alloy:latest
    container_name: prostriver-alloy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy